# Generated by Django 2.0.4 on 2018-04-18 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comm',
        ),
    ]
